---
name: pr-description-linter
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
permissions:
  contents: read
jobs:
  lint-pr-description:
    runs-on: ubuntu-latest
    env:
      PR_BODY: ${{github.event.pull_request.body}}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
    - id: run-pr-description-linter
      run: ./tools/linters/pr_description_linter.sh
